import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'common/index': 'src/common/index.ts',
    'security/index': 'src/security/index.ts',
    'config/index': 'src/config/index.ts',
    'email/index': 'src/email/index.ts',
    'logging/index': 'src/logging/index.ts',
    'orm/index': 'src/orm/index.ts',
    'orm/pool/index': 'src/orm/pool/index.ts',
  },
  format: ['cjs', 'esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  shims: false,
  target: 'es2023',
  tsconfig: './tsconfig.json',
  keepNames: true,
  external: [
    '@nestjs/common',
    '@nestjs/core',
    '@nestjs/config',
    '@nestjs/jwt',
    '@nestjs/passport',
    '@nestjs/swagger',
    '@nestjs/throttler',
    '@mikro-orm/core',
    '@mikro-orm/migrations',
    '@mikro-orm/nestjs',
    '@mikro-orm/postgresql',
    '@mikro-orm/seeder',
    'class-transformer',
    'class-validator',
    'reflect-metadata',
    'passport-jwt',
    '@sentry/nestjs',
    '@willsoto/nestjs-prometheus',
    'prom-client',
    'resend',
    'passport',
    'express',
    'rxjs',
    'rxjs/operators',
  ],
});
